# Writes build_stamp.cpp with the moment of the build, for the About panel.
# Run by the build, not by configure, so every build has its own time: a
# __DATE__ in a source file only moves when that file is recompiled.
# The file is rewritten only when the minute has changed, so a build with
# nothing to do does not relink the app.
string(TIMESTAMP NOW "%s" UTC)
math(EXPR MINUTE "${NOW} / 60 * 60")
set(TEXT "// Generated by native/cmake/build_stamp.cmake. Do not edit.\n#include \"app/build_stamp.hpp\"\n\nnamespace a2e::native {\nconst long long BUILD_TIME = ${MINUTE};\n}\n")
if(EXISTS "${OUT}")
  file(READ "${OUT}" OLD)
endif()
if(NOT "${OLD}" STREQUAL "${TEXT}")
  file(WRITE "${OUT}" "${TEXT}")
endif()
